apiVersion: v1
kind: ConfigMap
metadata:
  name: team5-prometheus-config
  namespace: skala3-finalproj-class2-team5
  labels:
    app: team5-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s

    scrape_configs:
      - job_name: team5-prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: team5-vision
        metrics_path: /metrics
        static_configs:
          - targets:
              - team5-vision:8002

      - job_name: team5-qdrant
        metrics_path: /metrics
        static_configs:
          - targets:
              - team5-qdrant:6333
