apiVersion: v1
kind: ConfigMap
metadata:
  name: team5-backend-config
  namespace: skala3-finalproj-class2-team5
  labels:
    app: team5-backend
data:
  BACKEND_PORT: "8000"
  POSTGRES_HOST: team5-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: safety
  APP_AUTH_COOKIE_SECURE: "false"
  APP_AUTH_COOKIE_SAME_SITE: Lax
  APP_MINIO_ENDPOINT: http://team5-minio:9000
  APP_MINIO_BUCKET: safety-files
  APP_CORS_ALLOWED_ORIGINS: http://team5-iveri.skala25a.project.skala-ai.com,http://localhost:3000
  APP_FASTAPI_BASE_URL: http://team5-fastapi:8001
