apiVersion: v1
kind: ConfigMap
metadata:
  name: team5-redis-config
  namespace: skala3-finalproj-class2-team5
  labels:
    app: team5-redis
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0
    protected-mode no
    maxmemory 200mb
    maxmemory-policy allkeys-lru
    appendonly no
    save ""
