apiVersion: v1
kind: Service
metadata:
  name: team5-qdrant
  namespace: skala3-finalproj-class2-team5
  labels:
    app: team5-qdrant
spec:
  type: ClusterIP
  selector:
    app: team5-qdrant
  ports:
    - name: http
      port: 6333
      targetPort: http
    - name: grpc
      port: 6334
      targetPort: grpc
