apiVersion: v1
kind: Service
metadata:
  name: team5-minio
  namespace: skala3-finalproj-class2-team5
  labels:
    app: team5-minio
spec:
  type: ClusterIP
  selector:
    app: team5-minio
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
